=== RajbhandariAnnie/Gift-Card-Store/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="store">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="storeDetails">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="storeName" type="xs:string" />
              <xs:element name="address" type="xs:string" />
              <xs:element name="Phone">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="[0-9]{10}" />
                    </xs:restriction>
                    </xs:simpleType>
              </xs:element>
              <xs:element name="website" type="xs:string" />
              <xs:element name="email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                        </xs:restriction>
                        </xs:simpleType>
              </xs:element>
              <xs:element name="logo">
                <xs:complexType>
                  <xs:attribute name="format" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="giftCard">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="card" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="card_code" minOccurs="0" type="xs:string" />
                    <xs:element name="card_name" type="xs:string" />
                    <xs:element name="cost">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="currency" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="validity" type="xs:string" />
                    <xs:element name="number_of_users" type="xs:string" />
                    <xs:element name="discountVouchers">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="type" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="free_delivery" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="type" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="is_available" minOccurs="0" type="xs:string" />
                    <xs:element name="available_quantity" minOccurs="0" type="xs:string" />
                    <xs:element name="used_quantity" minOccurs="0" type="xs:string" />
                    <xs:element name="countries_accepted" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="country" maxOccurs="unbounded">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="US"/>
                                            <xs:enumeration value="IN"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="physical" />
                        <xs:enumeration value="digital" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RajbhandariAnnie/Gift-Card-Store/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <storeDetails>
        <storeName>Annie's Store</storeName>
        <address>Lond St</address>
        <Phone>9805667717</Phone>
        <website>www.giftcardstore.com</website>
        <email>Store@gmail.com</email>
        <logo format="png"></logo>
    </storeDetails>
    <giftCard>
        <card type="physical">
            <card_name>Gift Card</card_name>
            <cost currency="USD">10.00</cost>
            <validity>1 month</validity>
            <number_of_users>100</number_of_users>
            <discountVouchers type="percentage">10</discountVouchers>
            <free_delivery type="boolean">true</free_delivery>
            <is_available>true</is_available>
            <available_quantity>100</available_quantity>
            <used_quantity>0</used_quantity>
            <countries_accepted>
                <country>US</country>
                <country>IN</country>
            </countries_accepted>
        </card>
        <card type="digital">
            <card_code>9876</card_code>
            <card_name>e-Gift Card</card_name>
            <cost currency="USD">10.00</cost>
            <validity>2 years</validity>
            <number_of_users>100</number_of_users>
            <discountVouchers type="amount">10.00</discountVouchers>
        </card>
        <card type="physical">
            <card_name>Gift Card</card_name>
            <cost currency="USD">12.00</cost>
            <validity>1 week</validity>
            <number_of_users>36</number_of_users>
            <discountVouchers type="percentage">40</discountVouchers>
        </card>
        <card type="physical">
            <card_name>Gift Card</card_name>
            <cost currency="USD">14.00</cost>
            <validity>2 weeks</validity>
            <number_of_users>40</number_of_users>
            <discountVouchers type="percentage">30</discountVouchers>
        </card>
        <card type="digital">
            <card_name>Gift Card</card_name>
            <cost currency="USD">15.00</cost>
            <validity>1 week</validity>
            <number_of_users>50</number_of_users>
            <discountVouchers type="percentage">45</discountVouchers>
        </card>
    </giftCard>
</store>
